version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Instalar dependencias
          command: npm install 
      - run:
          name: Correr test
          command: npm test